### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by PeterGilles** [mbarnig/Marylux-648-TTS-Corpus#15]
Moien,
dee Link hei geet net:
Archive including audio files sampled with 16000 Hz : MARYLUX-648-16000Hz.zip

**Comment by mbarnig** [comment]
Mäin Feeler.
Ech hat vergiess no enger Verbesserung dës Datei erëm an de Release-Depot opzelueden.
Elo fonctionéiert de Link.
