### ISSUE TITLE
sampling rate

### ISSUE THREAD

**Issue by PeterGilles** [mbarnig/Marylux-648-TTS-Corpus#16]
Bei dësen Dateien ass d'Sampling rate bei 22050 Hz amplaz 16000 Hz.

<img width="244" alt="Bildschirmfoto 2022-01-14 um 23 42 07" src="https://user-images.githubusercontent.com/3244485/149594651-ca570230-75f4-4921-9e78-25cec37122b3.png">

**Comment by mbarnig** [comment]
Merci fir ären Hiweis.

Mistère?

Ech hunn e klengen Programm gemaach fir d'Sampling-Rate ze kontrolléieren.

```python
import os
import wave
file_path = '/home/mbarnig/MARYLUX-648/Marylux-648-16000Hz/wavs/'
for file_name in os.listdir(file_path):
with wave.open(file_path + file_name, "rb") as wave_file:
frame_rate = wave_file.getframerate()
if frame_rate != 16000:
print(file_name + " : " + str(frame_rate))

>>>
marylux_lb-wiki-0240.wav : 22050
marylux_lb-wiki-0543.wav : 22050
marylux_lb-wiki-0519.wav : 22050
marylux_lb-wiki-0156.wav : 22050
marylux_lb-wiki-0094.wav : 22050
marylux_lb-wiki-1292.wav : 22050
marylux_lb-wiki-0440.wav : 22050
marylux_lb-wiki-1021.wav : 22050
marylux_lb-wiki-0498.wav : 22050
marylux_lb-wiki-0343.wav : 22050
marylux_lb-wiki-0372.wav : 22050
```
Ech hunn de ganzen Marylux-Corpus  mat 16KHz nei gesampelt an de zip-Archiv am Depot ersat.
D'Audiodateien mat 16000 Hz sinn elo och selwecht normaliséiert wéi déi mat 22050 Hz.

Ech hunn  déi éischte Kéier selwer den 16Kz Corpus gëschter benotzt mat mengem éischten Speech-to-Text Modell. Déi falsch Sampling-Rate bei deenen 11 Dateien gouf net gemellt, villäicht goufen se och automatesch konvertéiert. Ech hunn de ganzen COQUI-STT Code nach net analyséiert.

Op jiddwer Fall  sinn déi éischt STT-Resultater encourageant an ech fueren mat Begeeschterung weider.

**Comment by mbarnig** [comment]
De COQUI-STT code mécht effektiv eng automatesch Konversioun vun der sampling-rate:   
```  
    normalize_sample_rate: bool = field(
        default=True,
        metadata=dict(
            help="normalize sample rate of all train_files to --audio_sample_rate"
        ),
    )
```

**Comment by mbarnig** [comment]
I did a final check and updated the archives on 17.1.2021.
