### ISSUE TITLE
Feelend Transkriptiounen

### ISSUE THREAD

**Issue by PeterGilles** [mbarnig/Marylux-648-TTS-Corpus#17]
marylux_lb-wiki-1021: Moulin-à-Vent, Fleurie, Chiroubles, Morgon, Regnié, Côte-de-Brouilly a Brouilly.

marylux_lb-wiki-1292: D'Schleise sollten dräi Komma nonnzeg mol siwenanzwanzeg Komma Null dräi Meeter hunn an d'Breet fir den Tunnel war op fënnef Komma fënnefanachtzeg Meeter festgeluecht

**Comment by mbarnig** [comment]
Mäin Feeler.

Ech hat déi zwou Reien a mengem lokalen Environnement verbessert an vergiess zip-Archiver upzedaten. De Feeler ass och nach an der neier 16KHz Datei.

Déi drëtt Kolonn an der `marylux.csv` Datei enthält den "clean-text" deen ech fir TTS benotzen.
Déi zweet Kolonn ass den "raw-text" a sollt eigentlech Zuelen, Ofkierzungen, grouss a kléng Buschtawen asw enthalen. Well mäin `num2word`Skript nach net  faerdeg steet an der zweeter Kolonn elo e Mischmasch a bei den Zeilen 1021 an 1292 ass se eidel.

```
marylux_lb-wiki-1021| |moulin-à-vent, fleurie, chiroubles, morgon, regnié, côte-de-brouilly a brouilly.
marylux_lb-wiki-1292| |d'schleise sollten dräi-komma-nonzég mol siwen-an-zwanzeg-komma-null-dräi meter hunn an d'breet fir den tunnel war op fënnef-komma-fënnef-an-achtzeg meter festgeluecht.
```

Ech hunn déi zweet Kolonn verbessert esou dass den Ënnerscheed mam "clean-text" nëmmen nach Grouss-a Klengschreiwung ass fir eng koherent Basis ze hunn. Ech ersetzen haut déi zwou zip-Dateien mat de verbesserte Versiounen nodeems ech nach eng Kéier alles iwwerpréift hunn.

Ech preparéieren eng nei Datei mam Original Marylux "raw-text" fir den `num2word` Skript ze testen a mam manuell erstallten "clean-text" ze vergläichen.

Ech muss och eng nei Datei fir STT erstellen well de Format ganz anescht ass wéi beim TTS.

Et bleift spannend.

**Comment by mbarnig** [comment]
I did a final check and updated the archives on 17.1.2021 with the following included README :     
```   
Dataset : Marylux-648-TTS-Corpus
Author : Marco BARNIG mbarnig@pt.lu
Github: https://github.com/mbarnig/Marylux-648-TTS-Corpus

Archive content : 
* folder /wavs with audio files sampled with 16000Hz
* file raw_transcription.txt with sorted raw text lines
* file clean_transcription.txt with sorted cleaned text lines
* file phonemized_transcription.txt with sorted phonemized text lines
* file audio_filenames.txt with sorted pathes to audio files
* file audio_filesizes.txt with sorted size values of the audio files
* file marylux.csv : list in LJSpeech format ready for training with COQUI-TTS models
* file marylux_phonemes.csv : list in LJSpeech format ready for training with other TTS models

Description :
To assemble a dedicated csv file for TTS training, the following linux command can be used :

paste -d "|" file_1.txt file_2.txt  file_n.txt > new_name.csv

-d specifies the delimiter symbol to separate csv columns

Last update: 17.1.2022
```
